from components.power_production.solar_panel import SolarPanel
from components.power_production.wind_turbine import WindTurbine
from components.power_production.power_production_manager import PowerProductionManager
